
mode: "train"    # "train", "infer"
run_name: ""
run_dir: "./runs/"
comment: ""    # 其他备注信息

dataset: {
  name: "",
  train_dirs: [ "../datasets/gid15_256/train" ],
  val_dirs: [ "../datasets/gid15_256/val" ],
  test_dirs: [ "../datasets/gid15_256/val" ],
  cls_info: {
    background: 0,
    class1: 1,
    class2: 2,
    class3: 3,
    class4: 4,
    class5: 5,
    class6: 6,
    class7: 7,
    class8: 8,
    class9: 9,
    class10: 10,
    class11: 11,
    class12: 12,
    class13: 13
  },
  ignore_index: 255,
}

network: {
  type: "custom",    # "smp, ""custom", ...
  arch: "SegFormer",
  encoder: "mit_b3",
  in_size: 256,
  in_channel: 3,
  out_channel: 14,
  pretrained: "imagenet"
}

optimizer: {
  type: "AdamW",
  lr: 0.0001,
#  betas: [0.9, 0.999],
  weight_decay: 0.01,
}

train: {
  epochs: 40,
  batch_size: 8,
  smoothing: 0.1,
  save_inter: -1,  # 保存间隔(epoch), 小于1表示不备份
  plot: true
}

infer: {
  l1_win_sz: 2688,  # (256-128)*19+256=2688
  l1_overlap: 128,
  l2_win_sz: 256,
  l2_overlap: 128,
  batch_size: 1,
  tta: false,
}
}

